# Test the performance of the model

## Occurrence of symmetry equivalent structures

### Binary Quadratic Model

In [39]:
from quantum_computing_functions import *
from quantum_computing_postprocessing import *

from dwave.embedding.chain_strength import  uniform_torque_compensation

import numpy as np
import pandas as pd

from pymatgen.core.structure import Structure
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.io.ase import AseAtomsAdaptor

from ase.visualize import view

from pymatgen.ext.matproj import MPRester

from ase.visualize import view
from pymatgen.io.ase import AseAtomsAdaptor

'''import sys
sys.path.insert(1,'/Users/brunocamino/Desktop/Imperial/crystal-code-tools/crystal_functions/crystal_functions')
from file_readwrite import Crystal_gui
from convert import *'''

'''from crystal_functions.file_readwrite import *
from execute import runcry'''

'from crystal_functions.file_readwrite import *\nfrom execute import runcry'

In [2]:
from pymatgen.core.structure import Structure
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
import copy
import numpy as np

lattice = np.array([[ 1.233862, -2.137112,  0.      ],
                   [ 1.233862,  2.137112,  0.      ],
                   [ 0.      ,  0.      ,  8.685038]])

graphene = Structure(lattice, species=['C','C'], coords=[[2/3, 1/3, 0. ],[1/3, 2/3, 0.]])
graphene = SpacegroupAnalyzer(graphene).get_conventional_standard_structure()

n_supercell = 2
scaling_matrix = np.identity(3)*n_supercell
scaling_matrix[2][2] = 1
graphene_supercell = copy.deepcopy(graphene)
graphene_supercell.make_supercell(scaling_matrix)
structure = graphene_supercell
graphene_supercell.num_sites

8

In [896]:
view(AseAtomsAdaptor().get_atoms(graphene_supercell))

<Popen: returncode: None args: ['/Users/brunocamino/miniconda3/envs/qc/bin/p...>

# Formation energy

In [18]:
with MPRester("p5vAQV3F1QuxFcxVT") as m:    
    graphite_pmg = m.get_structure_by_material_id("mp-48")

In [39]:
graphite_gui = cry_pmg2gui(graphite)

In [41]:
write_crystal_gui('./data/crystal/graphite.gui',graphite_gui)

In [28]:
SpacegroupAnalyzer(graphite_pmg).get_space_group_operations()

[Rot:
 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]
 tau
 [0. 0. 0.],
 Rot:
 [[-1.  0.  0.]
  [ 0. -1.  0.]
  [ 0.  0. -1.]]
 tau
 [0. 0. 0.],
 Rot:
 [[ 1. -1.  0.]
  [ 1.  0.  0.]
  [ 0.  0.  1.]]
 tau
 [0.  0.  0.5],
 Rot:
 [[-1.  1.  0.]
  [-1.  0.  0.]
  [ 0.  0. -1.]]
 tau
 [0.  0.  0.5],
 Rot:
 [[ 0. -1.  0.]
  [ 1. -1.  0.]
  [ 0.  0.  1.]]
 tau
 [0. 0. 0.],
 Rot:
 [[ 0.  1.  0.]
  [-1.  1.  0.]
  [ 0.  0. -1.]]
 tau
 [0. 0. 0.],
 Rot:
 [[-1.  0.  0.]
  [ 0. -1.  0.]
  [ 0.  0.  1.]]
 tau
 [0.  0.  0.5],
 Rot:
 [[ 1.  0.  0.]
  [ 0.  1.  0.]
  [ 0.  0. -1.]]
 tau
 [0.  0.  0.5],
 Rot:
 [[-1.  1.  0.]
  [-1.  0.  0.]
  [ 0.  0.  1.]]
 tau
 [0. 0. 0.],
 Rot:
 [[ 1. -1.  0.]
  [ 1.  0.  0.]
  [ 0.  0. -1.]]
 tau
 [0. 0. 0.],
 Rot:
 [[ 0.  1.  0.]
  [-1.  1.  0.]
  [ 0.  0.  1.]]
 tau
 [0.  0.  0.5],
 Rot:
 [[ 0. -1.  0.]
  [ 1. -1.  0.]
  [ 0.  0. -1.]]
 tau
 [0.  0.  0.5],
 Rot:
 [[ 1.  0.  0.]
  [ 1. -1.  0.]
  [ 0.  0. -1.]]
 tau
 [0.  0.  0.5],
 Rot:
 [[-1.  0.  0.]
  [-1.  1.  0.]
 

In [38]:
graphene_gui = cry_pmg2gui(graphene_supercell,dimensionality=2)
write_crystal_gui('./data/crystal/graphene.gui',graphene_gui)

In [48]:
graphene_1v = copy.deepcopy(graphene_supercell)
graphene_1v.remove_sites([0])
graphene_1v_gui = cry_pmg2gui(graphene_1v)
write_crystal_gui('./data/crystal/graphene_1v.gui',graphene_1v_gui)

In [55]:
E_graphite = Crystal_output().read_cry_output('data/crystal/graphite.out').get_final_energy()
E_graphene = Crystal_output().read_cry_output('data/crystal/graphene.out').get_final_energy()
E_graphene_1v = Crystal_output().read_cry_output('data/crystal/graphene_1v.out').get_final_energy()

In [57]:
E_graphite_atom = E_graphite/graphite.num_sites
E_graphene_atom = E_graphene/graphene.num_sites
E_graphite_1v_atom = E_graphite/graphene_1v.num_sites


In [58]:
E_graphene_atom

-9321.11994268472

In [59]:
E_graphite_1v_atom

-243.69344321171502

# Build discrete QUBO

## Vacancies

#### Concentration

In [5]:
Q_const = build_qubo_discrete_constraints(structure,[6,0],concentration=[7,1],lambda_1 = 1, theta=1) 


array([[-1,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, -2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, -1,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, -2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, -2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, -1,  2,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, -2,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, -1,  2,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, -2,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  2,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -2,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  2,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,

#### Chemical potential

In [ ]:
Q_const = build_qubo_discrete_constraints(structure,[6,0],chem_potential=[0,-1],lambda_1 = 1, theta=1) 

#### Full model

In [6]:
species=[6,0]
parameters = [[-1,0,0]]
concentration = [7,1]
bqm = build_quadratic_model_discrete(structure ,species, parameters,
    concentration = concentration, chem_potential=None, max_neigh = 1, alpha=1,lambda_1 = 2, theta=10)
build_qubo_matrix(bqm)

array([[-36.,  20.,   4.,   0.,   4.,   0.,   4.,   0.,   3.,   0.,   3.,
          0.,   3.,   0.,   4.,   0.],
       [  0., -12.,   0.,   4.,   0.,   4.,   0.,   4.,   0.,   4.,   0.,
          4.,   0.,   4.,   0.,   4.],
       [  0.,   0., -36.,  20.,   4.,   0.,   4.,   0.,   3.,   0.,   3.,
          0.,   4.,   0.,   3.,   0.],
       [  0.,   0.,   0., -12.,   0.,   4.,   0.,   4.,   0.,   4.,   0.,
          4.,   0.,   4.,   0.,   4.],
       [  0.,   0.,   0.,   0., -36.,  20.,   4.,   0.,   3.,   0.,   4.,
          0.,   3.,   0.,   3.,   0.],
       [  0.,   0.,   0.,   0.,   0., -12.,   0.,   4.,   0.,   4.,   0.,
          4.,   0.,   4.,   0.,   4.],
       [  0.,   0.,   0.,   0.,   0.,   0., -36.,  20.,   4.,   0.,   3.,
          0.,   3.,   0.,   3.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0., -12.,   0.,   4.,   0.,
          4.,   0.,   4.,   0.,   4.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., -36.,  20.,   4.,
          0.,   4.,   

In [41]:
species=[6,0]
parameters = [[-1,0,0]]
chem_potential = [0.5,0]
bqm = build_quadratic_model_discrete(structure ,species, parameters,
    concentration = None, chem_potential=chem_potential, max_neigh = 1, alpha=1,lambda_1 = 2, theta=10)
build_qubo_matrix(bqm)

array([[ -9.5,  20. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,  -1. ,
          0. ,  -1. ,   0. ,  -1. ,   0. ,   0. ,   0. ],
       [  0. , -10. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,
          0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [  0. ,   0. ,  -9.5,  20. ,   0. ,   0. ,   0. ,   0. ,  -1. ,
          0. ,  -1. ,   0. ,   0. ,   0. ,  -1. ,   0. ],
       [  0. ,   0. ,   0. , -10. ,   0. ,   0. ,   0. ,   0. ,   0. ,
          0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [  0. ,   0. ,   0. ,   0. ,  -9.5,  20. ,   0. ,   0. ,  -1. ,
          0. ,   0. ,   0. ,  -1. ,   0. ,  -1. ,   0. ],
       [  0. ,   0. ,   0. ,   0. ,   0. , -10. ,   0. ,   0. ,   0. ,
          0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,  -9.5,  20. ,   0. ,
          0. ,  -1. ,   0. ,  -1. ,   0. ,  -1. ,   0. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. , -10. ,   0. ,
          0. ,   0. ,   0.

In [42]:
from dwave.system import EmbeddingComposite, DWaveSampler

sampler = EmbeddingComposite(DWaveSampler())

sampleset = sampler.sample(bqm, num_reads=1000)

In [43]:
dataframe = sampleset.to_pandas_dataframe()
convert_df(dataframe,2)

0  1  2  3  4  5  6  7  chain_break_fraction  energy  num_occurrences
0    1  1  1  1  1  1  1  1                   0.0   -88.0              181
1    1  1  0  1  1  1  1  1                   0.0   -85.5               34
2    1  1  1  1  0  1  1  1                   0.0   -85.5               31
3    1  1  1  1  1  0  1  1                   0.0   -85.5               24
4    1  0  1  1  1  1  1  1                   0.0   -85.5               37
..  .. .. .. .. .. .. .. ..                   ...     ...              ...
177  0  0  0  0  1  0  1  0                   0.0   -79.0                1
178  1  0  0  1  0  0  0  0                   0.0   -79.0                3
179  1  0  0  0  0  0  0  1                   0.0   -79.0                1
180  1  1  0  0  0  0  0  0                   0.0   -79.0                2
181  0  0  1  0  0  1  0  0                   0.0   -79.0                1

[182 rows x 11 columns]

## Solid solutions

In [14]:
from crystal_functions.file_readwrite import * 
from crystal_functions.convert import * 
from crystal_functions.execute import *


from pymatgen.core.structure import Structure
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
import copy
import numpy as np

lattice = np.array([[ 1.233862, -2.137112,  0.      ],
                   [ 1.233862,  2.137112,  0.      ],
                   [ 0.      ,  0.      ,  8.685038]])

graphene = Structure(lattice, species=['C','C'], coords=[[2/3, 1/3, 0. ],[1/3, 2/3, 0.]])
graphene = SpacegroupAnalyzer(graphene).get_conventional_standard_structure()

n_supercell = 2
scaling_matrix = np.identity(3)*n_supercell
scaling_matrix[2][2] = 1
graphene_supercell = copy.deepcopy(graphene)
graphene_supercell.make_supercell(scaling_matrix)
structure = graphene_supercell
graphene_supercell.num_sites

8

### Graphene pure

In [26]:
crystal_input = Crystal_input().from_file('./data/crystal/graphene.d12')

crystal_gui = cry_pmg2gui(graphene_supercell)
write_crystal_gui('./data/crystal/graphene_8.gui',crystal_gui)
write_crystal_input('./data/crystal/graphene_8.d12',crystal_input)

#runcry('./data/crystal/graphene_8')

crystal_output = Crystal_output().read_cry_output('./data/crystal/graphene_8.out')
E_graphene = crystal_output.get_final_energy()
E_graphene_atom = E_graphene/graphene_supercell.num_sites


### C atom

In [45]:
E_C = Crystal_output().read_cry_output('./data/crystal/c.out').get_final_energy()
E_cc_bond = (E_graphene-(graphene_supercell.num_sites*E_C))/(graphene_supercell.num_sites*1.5)
E_cc_bond

-6.801866316724651

### N atom

In [30]:
E_N = Crystal_output().read_cry_output('./data/crystal/n.out').get_final_energy()

### Graphene 1 N

In [50]:
crystal_input = Crystal_input().from_file('./data/crystal/graphene.d12')

graphene_supercell.replace(0,7)

crystal_gui = cry_pmg2gui(graphene_supercell)
write_crystal_gui('./data/crystal/graphene_8_1N.gui',crystal_gui)
write_crystal_input('./data/crystal/graphene_8_1N.d12',crystal_input)

runcry('./data/crystal/graphene_8_1N')

crystal_output = Crystal_output().read_cry_output('./data/crystal/graphene_8_1N.out')
E_graphene_1N = crystal_output.get_final_energy()
E_graphene_1N_atom = E_graphene_1N/graphene_supercell.num_sites


#### method 1

In [49]:
E_cn_bond = (E_graphene_1N-((graphene_supercell.num_sites-1)*E_C + 1*E_N + 9*E_cc_bond))/3
E_cn_bond

-5.973544367641201

#### method 2

In [46]:
E_cn_bond = (E_graphene_1N-((graphene_supercell.num_sites-1)*E_C+E_N))/(graphene_supercell.num_sites*1.5)
E_cn_bond

-6.594785829453788

In [51]:
view(AseAtomsAdaptor().get_atoms(graphene_supercell))

<Popen: returncode: None args: ['/Users/brunocamino/miniconda3/envs/qc/bin/p...>

### Graphene 2 N

In [52]:
crystal_input = Crystal_input().from_file('./data/crystal/graphene.d12')

graphene_supercell.replace(0,7)
graphene_supercell.replace(4,7)

crystal_gui = cry_pmg2gui(graphene_supercell)
write_crystal_gui('./data/crystal/graphene_8_2N.gui',crystal_gui)
write_crystal_input('./data/crystal/graphene_8_2N.d12',crystal_input)

runcry('./data/crystal/graphene_8_2N')

crystal_output = Crystal_output().read_cry_output('./data/crystal/graphene_8_2N.out')
E_graphene_2N = crystal_output.get_final_energy()



#### method 1

In [55]:
E_nn_bond = (E_graphene_2N-((graphene_supercell.num_sites-2)*E_C + 2*E_N + 7*E_cc_bond +4*E_cn_bond))
E_nn_bond

-4.274455886279611

In [172]:
def build_ip_matrix(structure, species, parameters, alpha=100, max_neigh = 1,test=False):
    
    num_sites = structure.num_sites
    num_species = len(species)
    num_elements = num_sites*num_species
    
    distance_matrix = np.round(structure.distance_matrix,5)
    shells = np.unique(np.round(distance_matrix,5))
    
    if test == True:
        adjacency_matrix = build_adjacency_matrix(structure)
        param = [0,1,0,0]
    
    # Generate an all False matrix
    distance_matrix_filter = (distance_matrix == -1)

    
    # Only add the atoms within the shells up to max_neigh 
    for neigh in range(1,max_neigh+1):
        distance_matrix_filter +=  distance_matrix == shells[neigh]  

    # Buckingham
    #loop 
    
    ip_matrix = np.zeros((num_elements,num_elements))
    parameters = np.array(parameters)
    for i in range(num_sites):
        for j in range(i,num_sites):
            if distance_matrix_filter[i,j] == True:
                index = -1
                for k in range(num_species):
                    for l in range(k,num_species):
                        index += 1
                        param = parameters[index]
                        #print(i*num_species+k,j*num_species+l)
                        if test == True:
                            ip_matrix[i*num_species+k,j*num_species+l] = \
                            adjacency_matrix[i,j]*param
                        else:
                            ip_matrix[i*num_species+k,j*num_species+l] = \
                            param[0] * np.exp((-distance_matrix[i,j])/(param[1]))- \
                            ((param[2])/((distance_matrix[i,j])**6))
                        
                
    return np.round(ip_matrix,2)

In [72]:
build_qubo_matrix(build_bqm_discrete(structure,[12,14],[0.5,0.5], parameters, alpha=1, lambda_1=2, theta=10, max_neigh = 1))

[[-10.    20.     4.     0.     4.24   0.98   4.24   0.98]
 [  0.   -10.     0.     4.     0.     4.24   0.     4.24]
 [  0.     0.   -10.    20.     4.24   0.98   4.24   0.98]
 [  0.     0.     0.   -10.     0.     4.24   0.     4.24]
 [  0.     0.     0.     0.   -10.    20.     4.     0.  ]
 [  0.     0.     0.     0.     0.   -10.     0.     4.  ]
 [  0.     0.     0.     0.     0.     0.   -10.    20.  ]
 [  0.     0.     0.     0.     0.     0.     0.   -10.  ]]


array([[-10,  20,   4,   0,   4,   0,   4,   0],
       [  0, -10,   0,   4,   0,   4,   0,   4],
       [  0,   0, -10,  20,   4,   0,   4,   0],
       [  0,   0,   0, -10,   0,   4,   0,   4],
       [  0,   0,   0,   0, -10,  20,   4,   0],
       [  0,   0,   0,   0,   0, -10,   0,   4],
       [  0,   0,   0,   0,   0,   0, -10,  20],
       [  0,   0,   0,   0,   0,   0,   0, -10]])

In [71]:
parameters = [[2457.243, 0.2610,  0.00],
             [2457.243, 0.2610,  0.00],
             [2457.243, 0.2610,  0.00]]
             
parameters = [[1.,1.,0.],
            [2,2,0.],
             [1,1,0.]]
             

#build_bqm_discrete(structure,species,concentrations, parameters, weight=100, max_neigh = 1)
#build_bqm_discrete(structure,[12,14],[0.5,0.5], parameters, weight=100, max_neigh = 1)

In [891]:
df = sampleset.to_pandas_dataframe()
def convert_df(df,remove_unfeasible=True):
    
    num_sites = sum([type(x) == int for x in df.columns])
    sites = df.iloc[:,0:num_sites].to_numpy()
    unfeasible = np.where(np.prod((sites[:,::2]+sites[:,1::2]),axis=1) != 1)[0]
    df.drop(unfeasible, inplace=True)
    
    new_labels = df.iloc[:,0:num_sites].to_numpy()[:,::2]
    df.drop(np.arange(num_sites),axis=1,inplace=True)
    
    new_col = {}
    for i in range(int(num_sites/2)):
        new_col[i] = new_labels[:,i].tolist()
    return df
convert_df(df)

chain_break_fraction  energy  num_occurrences
0                0.000000 -2316.0                1
1                0.000000 -2314.0                1
2                0.000000 -2314.0                2
3                0.000000 -2314.0                1
4                0.000000 -2314.0                1
..                    ...     ...              ...
945              0.027778 -2203.0                1
959              0.027778 -2162.0                1
981              0.055556 -2271.0                1
985              0.055556 -2207.0                1
986              0.055556 -2111.0                1

[761 rows x 3 columns]

In [717]:
ar = df.iloc[:,0:36].to_numpy()
np.sum(df['num_occurrences'].to_numpy()[np.where(np.sum(ar[:,::2],axis=1) == 17)[0]])
ar.shape

(490, 36)

In [749]:
keep = np.where(np.sum((ar[:,::2]+ar[:,1::2])-np.ones((ar.shape[0],int(ar.shape[1]/2))),axis=1) == 0. )
not_keep = np.where(np.sum((ar[:,::2]+ar[:,1::2])-np.ones((ar.shape[0],int(ar.shape[1]/2))),axis=1) != 0. )[0]
#aa = np.sum((ar[:,::2]+ar[:,1::2])-np.ones((ar.shape[0],int(ar.shape[1]/2))),axis=1) 
print(np.where(np.sum(ar[keep][:,::2],axis=1) == 17))
not_keep2 = np.where(np.sum(ar[keep][:,::2],axis=1) != 17)[0]
np.sum(df['num_occurrences'].to_numpy()[keep][np.where(np.sum(ar[keep][:,::2],axis=1) == 17)])
df.drop(not_keep)
df.drop(not_keep2)

(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  41,  42,  43,  44,
        45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
        78,  79,  80,  82,  83, 111, 112, 117, 118, 119, 120, 121, 124,
       125, 126, 128, 129, 130, 131, 134, 136, 139, 140, 142, 157, 158,
       160, 161, 162, 166, 170, 171, 172, 174, 178, 179, 180, 181, 184,
       187, 190, 191, 192, 195, 208, 209, 210, 218, 226, 228, 229, 230]),)


0  1  2  3  4  5  6  7  8  9  ...  29  30  31  32  33  34  35  \
0    1  0  1  0  1  0  1  0  1  0  ...   0   1   0   1   0   1   0   
1    0  1  1  0  1  0  1  0  1  0  ...   0   1   0   1   0   1   0   
2    1  0  1  0  1  0  1  0  0  1  ...   0   1   0   1   0   1   0   
3    1  0  1  0  1  0  1  0  1  0  ...   0   1   0   1   0   1   0   
4    1  0  1  0  1  0  1  0  1  0  ...   0   1   0   1   0   1   0   
..  .. .. .. .. .. .. .. .. .. ..  ...  ..  ..  ..  ..  ..  ..  ..   
485  1  0  1  0  1  0  0  1  1  0  ...   0   0   0   1   0   1   0   
486  1  0  1  0  1  0  1  0  1  1  ...   0   1   0   1   0   1   0   
487  1  0  0  0  0  0  1  0  1  0  ...   0   1   0   1   0   0   1   
488  1  0  1  0  1  0  1  0  1  0  ...   0   1   0   1   0   1   0   
489  0  0  1  0  1  0  1  0  1  0  ...   0   0   0   1   0   1   0   

     chain_break_fraction  energy  num_occurrences  
0                0.000000  -760.0               27  
1                0.000000  -760.0                8  
2                0.000000  -760.0               34  
3                0.000000  -760.0               42  
4                0.000000  -760.0               16  
..                    ...     ...              ...  
485              0.083333  -732.0                1  
486              0.083333  -736.0                1  
487              0.027778  -708.0                1  
488              0.055556  -748.0                1  
489              0.111111  -706.0                1  

[334 rows x 39 columns]